import { MarketBriefCard } from "@/components/terminal/research/MarketBriefCard";
import { TickerResearchCard } from "@/components/terminal/research/TickerResearchCard";

export default function ResearchPage() {
  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-sm font-medium text-text-primary">AI Research Assistant</h1>
        <p className="text-xs text-text-muted">
          Generated by Gemini from this app&apos;s own real data (market news, earnings, company overview,
          ratios, recent headlines) — never invented. Not investment advice.
        </p>
      </div>

      <MarketBriefCard />
      <TickerResearchCard />
    </div>
  );
}
